### PR TITLE
Designated Queues per Resource Capability

### PR DESCRIPTION
**Pull request by JVickery-TBS**
feat(dev): designated queues;

- Add capability for designated queues per resource.

### CODE REVIEW

**Comment by wardi** [comment]
How does this change worker behaviour?

**Comment by JVickery-TBS** [comment]
@wardi It would not change how any of the code is run, it would just put the "load to datastore" job in its own REDIS queue with the name of the Resource ID.

I can add to our forks readme for this.

**Comment by wardi** [comment]
What does putting a job in its own queue do? Just make it easier to report progress on?

**Comment by JVickery-TBS** [comment]
@wardi nothing really, you would need to run a worker with that queue like `ckan jobs worker <queue name>` for it to run. But it allows for creating a swarm service on job workers.

**Comment by JVickery-TBS** [comment]
@wardi I have added a new section to the README for our fork, describing some of the main changes of our fork. This includes the new capability for the dedicated queues.

**Review by wardi — APPROVED** [review]

**Pull request merged**
